### ISSUE TITLE
Color difference between avatars generated on mobile and desktop

### ISSUE THREAD

**Issue by sbermingham93** [DiceBear/avatars#394] opened 2023-12-18 17:15 UTC
We are using @dicebear/core, and @dicebear/collection version ^7.0.1 for both

import { createAvatar } from "@dicebear/core";
import { botttsNeutral } from "@dicebear/collection";

...

const avatar = createAvatar(botttsNeutral, {
        seed: walletPubkey?.toString(),
      });
  
return avatar.toString();

...

For the same seed we are seeing different colors when rendered on mobile device and desktop device, both on chrome. (see both attached
<img width="1080" alt="Screenshot 2023-12-18 at 18 11 41" src="https://github.com/dicebear/api/assets/79837489/269613c3-b6bc-40f4-8ba8-554d50e97899">
)

![image0 (1)](https://github.com/dicebear/api/assets/79837489/3b034fd4-3640-427a-bae9-329c4c5e2819)

Presumably this is not as expected?

**Comment by sbermingham93** [comment] 2023-12-18 17:16
Also meant to say, thank you, your libraries are great, much appreciated!

**Comment by FlorianKoerner** [comment] 2023-12-18 20:50
Hi @sbermingham93 

Of course, there should be no differences. To help you better and to be able to reproduce the problem, I need the exact seed and other options that are used in your example. The operating system and browser version would also be helpful.

**Comment by sbermingham93** [comment] 2023-12-22 11:23
Hi, thank you for the reply.

The seed is: FViCMckurWzJok4mui4LBf9SQGAZnTsX9A1SppXDAnGm.

Desktop device is Macbook Pro running macOS Big Sur, browser is Chrome: Version 120.0.6099.109
Mobile device is IPhoneXR running IOS 17.1.1, browser is Chrome: Version Version 120.0.6099.119

So the code snippet to be used to repro (This was done from a react app)

1. install @dicebear/core, and @dicebear/collection version 7.0.1 for both

2. generate svg string with following code

import { createAvatar } from "@dicebear/core";
import { botttsNeutral } from "@dicebear/collection";

...

const avatar = createAvatar(botttsNeutral, {
seed: 'FViCMckurWzJok4mui4LBf9SQGAZnTsX9A1SppXDAnGm',
});

return avatar.toString();

3. Render the svg with "react-inlinesvg": "^4.0.5",
<SVG src={avatarSvgString} width={16} height={16} />

Let me know if you need any more information.

Thanks again!

**Comment by FlorianKoerner** [comment] 2023-12-28 14:40
Should be fixed with version `8.0.0-rc.2`. Can you confirm?

https://codesandbox.io/p/devbox/dicebear-394-7y5zsm

**Comment by sbermingham93** [comment] 2024-01-16 10:47
Hi thanks for putting in the fix! I have tested and seems to work for certain cases but not all

**Comment by sbermingham93** [comment] 2024-01-16 10:53
<img width="1728" alt="image (4)" src="https://github.com/dicebear/dicebear/assets/79837489/ffa228b4-bfec-4104-9e52-574590037ab7">

SEED: JA94JEt2iCHrPe9ABRsJFBccpsNcZC33YvsR7n684bmq

Operating System: MacOs 

Browser: Brave

Dicebear Versions:
"@dicebear/collection": "^8.0.0-rc.2",
"@dicebear/core": "^8.0.0-rc.2", 

Description:
See the yellow on one avatar, while red on the rest

**Comment by FlorianKoerner** [comment] 2024-01-20 08:30
Cannot reproduce your problem. To be able to help you, I need a public repository from you where the problem can be reproduced with little effort.

Brave
<img width="1312" alt="Bildschirmfoto 2024-01-20 um 09 26 28" src="https://github.com/dicebear/dicebear/assets/647303/109a3dee-c220-4ae8-8257-387942779db8">

Safari
<img width="1436" alt="Bildschirmfoto 2024-01-20 um 09 28 26" src="https://github.com/dicebear/dicebear/assets/647303/ec9361da-cfa5-43a0-93ad-6e953d054071">

**Closed as completed** 2024-02-02 15:30 UTC
